name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]
        cxx: [clang++-14, g++-11, cl]
        std: [11, 20]
        build_type: [Debug]
        generators: [Ninja]
        exclude:
          - os: windows-latest
            cxx: clang++-14
          - os: windows-latest
            cxx: g++-11
          - os: ubuntu-22.04
            cxx: cl
        include:
          - os: ubuntu-20.04
            cxx: g++-5
            std: 11
            build_type: Debug
            generators: Ninja
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH env
        if: matrix.cxx == 'cl'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install g++-5
        if: matrix.cxx == 'g++-5'
        run: |
          # Bellow two repos provide GCC 4.8, and 6.4
          sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ bionic main'
          sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ bionic universe'
          sudo apt install g++-5

      - name: Install dependencies on windows
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version

      - name: Install dependencies on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install cmake ninja
          ninja --version
          cmake --version

      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake \
            -S . \
            -B . \
            -G "${{matrix.generators}}" \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
            -DCMAKE_CXX_STANDARD:STRING=${{matrix.std}} \
            -DDS_BUILD_TESTS=ON

      - name: Build
        shell: bash
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Test
        shell: bash
        run: ctest --output-on-failure .
